"""add processing job worker leases

Revision ID: 2a42cc2b599f
Revises: b2085435f7b9
Create Date: 2026-07-18 23:11:05.809294

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a42cc2b599f"
down_revision: Union[str, Sequence[str], None] = "b2085435f7b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "processing_jobs",
        sa.Column(
            "last_processed_frame",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )

    op.alter_column(
        "processing_jobs",
        "last_processed_frame",
        server_default=None,
    )
    op.add_column(
        "processing_jobs", sa.Column("worker_id", sa.String(length=160), nullable=True)
    )
    op.add_column(
        "processing_jobs",
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "processing_jobs",
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "processing_jobs",
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_processing_jobs_lease_expires_at"),
        "processing_jobs",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_processing_jobs_worker_id"),
        "processing_jobs",
        ["worker_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_processing_jobs_worker_id"), table_name="processing_jobs")
    op.drop_index(
        op.f("ix_processing_jobs_lease_expires_at"), table_name="processing_jobs"
    )
    op.drop_column("processing_jobs", "lease_expires_at")
    op.drop_column("processing_jobs", "heartbeat_at")
    op.drop_column("processing_jobs", "claimed_at")
    op.drop_column("processing_jobs", "worker_id")
    op.drop_column("processing_jobs", "last_processed_frame")
    # ### end Alembic commands ###
