"""enforce unique video checksums

Revision ID: b2085435f7b9
Revises: ee64d0d2fdcc
Create Date: 2026-07-18 22:44:24.177794

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b2085435f7b9"
down_revision: Union[str, Sequence[str], None] = "ee64d0d2fdcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_videos_checksum_sha256"), table_name="videos")
    op.create_unique_constraint(
        op.f("uq_videos_checksum_sha256"), "videos", ["checksum_sha256"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_videos_checksum_sha256"), "videos", type_="unique")
    op.create_index(
        op.f("ix_videos_checksum_sha256"), "videos", ["checksum_sha256"], unique=False
    )
    # ### end Alembic commands ###
