"""create traffic intelligence core tables

Revision ID: ee64d0d2fdcc
Revises:
Create Date: 2026-07-18 14:27:51.260221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ee64d0d2fdcc"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cameras",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("stream_url", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "inactive",
                "active",
                "degraded",
                "offline",
                name="camera_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("configured_fps", sa.Float(), nullable=True),
        sa.Column("resolution_width", sa.Integer(), nullable=True),
        sa.Column("resolution_height", sa.Integer(), nullable=True),
        sa.Column(
            "configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cameras")),
    )
    op.create_index(op.f("ix_cameras_name"), "cameras", ["name"], unique=True)
    op.create_index(op.f("ix_cameras_status"), "cameras", ["status"], unique=False)
    op.create_table(
        "videos",
        sa.Column("camera_id", sa.Uuid(), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum(
                "upload",
                "camera_recording",
                "live_stream",
                name="video_source_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "queued",
                "processing",
                "completed",
                "failed",
                name="video_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("frames_per_second", sa.Float(), nullable=True),
        sa.Column("frame_count", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "video_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
            name=op.f("fk_videos_camera_id_cameras"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_videos")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_videos_storage_key")),
    )
    op.create_index(op.f("ix_videos_camera_id"), "videos", ["camera_id"], unique=False)
    op.create_index(
        op.f("ix_videos_checksum_sha256"), "videos", ["checksum_sha256"], unique=False
    )
    op.create_index(op.f("ix_videos_status"), "videos", ["status"], unique=False)
    op.create_table(
        "processing_jobs",
        sa.Column("video_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                name="processing_job_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("progress_percent", sa.Float(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("pipeline_name", sa.String(length=120), nullable=False),
        sa.Column("pipeline_version", sa.String(length=50), nullable=True),
        sa.Column(
            "model_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "job_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "progress_percent >= 0 AND progress_percent <= 100",
            name=op.f("ck_processing_jobs_progress_percent_range"),
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_processing_jobs_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_jobs")),
    )
    op.create_index(
        op.f("ix_processing_jobs_status"), "processing_jobs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_processing_jobs_video_id"),
        "processing_jobs",
        ["video_id"],
        unique=False,
    )
    op.create_table(
        "violation_events",
        sa.Column("video_id", sa.Uuid(), nullable=False),
        sa.Column("camera_id", sa.Uuid(), nullable=True),
        sa.Column("processing_job_id", sa.Uuid(), nullable=True),
        sa.Column("event_key", sa.String(length=160), nullable=False),
        sa.Column(
            "violation_type",
            sa.Enum(
                "no_helmet",
                "triple_riding",
                "red_light",
                "wrong_way",
                "lane_violation",
                "illegal_parking",
                "speeding",
                "mobile_phone",
                "seatbelt",
                name="violation_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "review_status",
            sa.Enum(
                "pending",
                "confirmed",
                "rejected",
                name="review_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("frame_number", sa.Integer(), nullable=True),
        sa.Column("track_id", sa.String(length=120), nullable=True),
        sa.Column("license_plate", sa.String(length=32), nullable=True),
        sa.Column("detection_confidence", sa.Float(), nullable=True),
        sa.Column("rule_confidence", sa.Float(), nullable=True),
        sa.Column("ocr_confidence", sa.Float(), nullable=True),
        sa.Column("evidence_image_key", sa.String(length=500), nullable=True),
        sa.Column("evidence_clip_key", sa.String(length=500), nullable=True),
        sa.Column("geometry", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "event_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "detection_confidence IS NULL OR (detection_confidence >= 0 AND detection_confidence <= 1)",
            name=op.f("ck_violation_events_detection_confidence_range"),
        ),
        sa.CheckConstraint(
            "ocr_confidence IS NULL OR (ocr_confidence >= 0 AND ocr_confidence <= 1)",
            name=op.f("ck_violation_events_ocr_confidence_range"),
        ),
        sa.CheckConstraint(
            "rule_confidence IS NULL OR (rule_confidence >= 0 AND rule_confidence <= 1)",
            name=op.f("ck_violation_events_rule_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
            name=op.f("fk_violation_events_camera_id_cameras"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["processing_job_id"],
            ["processing_jobs.id"],
            name=op.f("fk_violation_events_processing_job_id_processing_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_violation_events_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_violation_events")),
        sa.UniqueConstraint("event_key", name=op.f("uq_violation_events_event_key")),
    )
    op.create_index(
        "ix_violation_event_time_type",
        "violation_events",
        ["occurred_at", "violation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_violation_events_camera_id"),
        "violation_events",
        ["camera_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_violation_events_license_plate"),
        "violation_events",
        ["license_plate"],
        unique=False,
    )
    op.create_index(
        op.f("ix_violation_events_occurred_at"),
        "violation_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_violation_events_processing_job_id"),
        "violation_events",
        ["processing_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_violation_events_review_status"),
        "violation_events",
        ["review_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_violation_events_track_id"),
        "violation_events",
        ["track_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_violation_events_video_id"),
        "violation_events",
        ["video_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_violation_events_violation_type"),
        "violation_events",
        ["violation_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_violation_events_violation_type"), table_name="violation_events"
    )
    op.drop_index(op.f("ix_violation_events_video_id"), table_name="violation_events")
    op.drop_index(op.f("ix_violation_events_track_id"), table_name="violation_events")
    op.drop_index(
        op.f("ix_violation_events_review_status"), table_name="violation_events"
    )
    op.drop_index(
        op.f("ix_violation_events_processing_job_id"), table_name="violation_events"
    )
    op.drop_index(
        op.f("ix_violation_events_occurred_at"), table_name="violation_events"
    )
    op.drop_index(
        op.f("ix_violation_events_license_plate"), table_name="violation_events"
    )
    op.drop_index(op.f("ix_violation_events_camera_id"), table_name="violation_events")
    op.drop_index("ix_violation_event_time_type", table_name="violation_events")
    op.drop_table("violation_events")
    op.drop_index(op.f("ix_processing_jobs_video_id"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_status"), table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index(op.f("ix_videos_status"), table_name="videos")
    op.drop_index(op.f("ix_videos_checksum_sha256"), table_name="videos")
    op.drop_index(op.f("ix_videos_camera_id"), table_name="videos")
    op.drop_table("videos")
    op.drop_index(op.f("ix_cameras_status"), table_name="cameras")
    op.drop_index(op.f("ix_cameras_name"), table_name="cameras")
    op.drop_table("cameras")
    # ### end Alembic commands ###
